### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by owais** [jazzband/django-webpack-loader#246]
As it is obvious from the state of issues and pull-requests, I don't have the bandwidth to maintain the repo along with webpack-bundle-tracker. So, I'd like to give maintenance rights to others who might be interested and have experience maintaining OSS libs. I'd like to eventually transfer the repo to a new permanent maintainer whether an individual or an org. Please feel free to email me at owais@lone.pw if this is something you'd like to help with. Thanks.

**Comment by ilikerobots** [comment]
Thanks so much for you work on the project!

**Comment by owais** [comment]
Moved the project to JazzBand (https://jazzband.co). Help needed to set everything up and maintain the project.

https://github.com/jazzband/django-webpack-loader/issues/248

**Comment by owais** [comment]
Anyone interested in helping maintain the project can join JazzBand and start contributing. Hopefully over time we can find a new leader for the project.
